from __future__ import annotations

import difflib
from pathlib import Path

from src.infra.settings import APP_ENV_SPECS, BENCHMARK_ENV_SPECS, DEFAULT_BENCHMARK_CONFIG_PATH, EnvVarSpec, load_benchmark_env_defaults


README_APP_SETTINGS_HEADING = "### 4.1 애플리케이션 설정"
README_BENCHMARK_SETTINGS_HEADING = "### 4.2 벤치마크 설정"
README_SETTINGS_END_HEADING = "## 5. 검색 소스와 파일 제약"


def _serialize_env_value(value: str | int | float | bool | None) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return f'"{value}"'


def _format_readme_default(value: str | int | float | bool | None) -> str:
    if value is None:
        return "없음"
    if isinstance(value, bool):
        return f"`{'true' if value else 'false'}`"
    return f"`{value}`"


def _collect_sync_notes(specs: tuple[EnvVarSpec, ...]) -> list[str]:
    seen: set[str] = set()
    notes: list[str] = []
    for spec in specs:
        for note in spec.sync_notes:
            if note in seen:
                continue
            seen.add(note)
            notes.append(note)
    return notes


def _render_env_var_lines(spec: EnvVarSpec, value: str | int | float | bool | None) -> list[str]:
    lines = [f"# {note}" for note in spec.sync_notes]
    lines.append(f"{spec.env_name}={_serialize_env_value(value)}")
    return lines


def _render_readme_notes(specs: tuple[EnvVarSpec, ...]) -> list[str]:
    notes = _collect_sync_notes(specs)
    if not notes:
        return []

    lines = [
        "",
        "모델별 reasoning effort override 참고:",
        "",
    ]
    for note in notes:
        model_name, supported_values = note.split(":", maxsplit=1)
        lines.append(f"- `{model_name}`: {supported_values.strip()}")
    return lines


def _render_settings_table(
    specs: tuple[EnvVarSpec, ...],
    defaults: dict[str, str | int | float | bool | None] | None = None,
) -> list[str]:
    lines = [
        "| 이름 | 기본값 | 설명 |",
        "|---|---|---|",
    ]
    for spec in specs:
        default_value = spec.default if defaults is None else defaults[spec.env_name]
        lines.append(f"| `{spec.env_name}` | {_format_readme_default(default_value)} | {spec.description} |")
    return lines


def build_env_example_text(config_path: Path = DEFAULT_BENCHMARK_CONFIG_PATH) -> str:
    benchmark_defaults = load_benchmark_env_defaults(config_path)
    lines = [
        "# Generated by `uv run python script/sync_env_example.py`.",
        "# App defaults come from `src/infra/settings.py`.",
        "# Benchmark override defaults are copied from `data/benchmarks/config.toml`.",
        "",
        "# Required secrets",
    ]
    for spec in APP_ENV_SPECS[:2]:
        lines.append(f"{spec.env_name}=")

    lines.extend(
        [
            "",
            "# Application settings",
        ]
    )
    for spec in APP_ENV_SPECS[2:-3]:
        lines.extend(_render_env_var_lines(spec, spec.default))

    lines.extend(
        [
            "",
            "# Slack",
        ]
    )
    for spec in APP_ENV_SPECS[-3:]:
        lines.append(f"{spec.env_name}=")

    lines.extend(
        [
            "",
            "# Benchmark / Eval overrides",
        ]
    )
    for spec in BENCHMARK_ENV_SPECS:
        lines.extend(_render_env_var_lines(spec, benchmark_defaults[spec.env_name]))
    return "\n".join(lines).rstrip() + "\n"


def build_readme_app_settings_block() -> str:
    lines = [
        README_APP_SETTINGS_HEADING,
        "",
        "기준 파일:",
        "",
        "- 기본값 source of truth: `src/infra/settings.py`",
        "- 예시 환경 파일: `.env.example` (생성 산출물)",
        "- 동기화 명령: `uv run python script/sync_env_example.py`",
        "",
    ]
    lines.extend(_render_settings_table(APP_ENV_SPECS))
    lines.extend(_render_readme_notes(APP_ENV_SPECS))
    return "\n".join(lines).rstrip() + "\n"


def build_readme_benchmark_settings_block(config_path: Path = DEFAULT_BENCHMARK_CONFIG_PATH) -> str:
    lines = [
        README_BENCHMARK_SETTINGS_HEADING,
        "",
        "기준 파일:",
        "",
        "- 기본값 source of truth: `data/benchmarks/config.toml`",
        "- 환경 변수 override 정의: `src/infra/settings.py`",
        "- 예시 환경 파일: `.env.example` (config 값을 복사한 override 예시)",
        "- 동기화 명령: `uv run python script/sync_env_example.py`",
        "",
    ]
    lines.extend(_render_settings_table(BENCHMARK_ENV_SPECS, defaults=load_benchmark_env_defaults(config_path)))
    return "\n".join(lines).rstrip() + "\n"


def _replace_between(text: str, start_heading: str, end_heading: str, replacement_block: str) -> str:
    start_index = text.find(start_heading)
    end_index = text.find(end_heading)
    if start_index < 0 or end_index < 0 or end_index <= start_index:
        raise ValueError(f"README section markers were not found: {start_heading!r} -> {end_heading!r}")
    prefix = text[:start_index].rstrip()
    suffix = text[end_index:].lstrip("\n")
    return prefix + "\n\n" + replacement_block.rstrip() + "\n\n" + suffix


def sync_readme_settings_sections(
    readme_text: str,
    config_path: Path = DEFAULT_BENCHMARK_CONFIG_PATH,
) -> str:
    synced = _replace_between(
        readme_text,
        README_APP_SETTINGS_HEADING,
        README_BENCHMARK_SETTINGS_HEADING,
        build_readme_app_settings_block(),
    )
    return _replace_between(
        synced,
        README_BENCHMARK_SETTINGS_HEADING,
        README_SETTINGS_END_HEADING,
        build_readme_benchmark_settings_block(config_path),
    )


def build_unified_diff(path: Path, actual: str, expected: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(path),
            tofile=f"{path} (expected)",
            lineterm="",
        )
    )


__all__ = [
    "build_env_example_text",
    "build_readme_app_settings_block",
    "build_readme_benchmark_settings_block",
    "build_unified_diff",
    "sync_readme_settings_sections",
]
